server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

# see also https://stackoverflow.com/a/30296748
spring:
  jms:
    pub-sub-domain: true

logging:
  level:
    org:
      cloudfoundry:
        promregator: WARN

# To be enabled, if ActiveMQ logging shall be activated - see also http://activemq.apache.org/how-do-i-enable-debug-logging.html
#      apache:
#        activemq: DEBUG

    reactor:
      Mono:
        OnAssembly: WARN

# To be enabled, if you want to have Promregator -> CF Cloud Controller communication being logged
# Warning! This will expose internal and sensitive information in the logs!
#      ipc:
#        netty:
#          http: DEBUG
#          channel: DEBUG

# Enable this one, if you want to have network request logging on cloudfoundry-client level
#    cloudfoundry-client:
#      request: DEBUG
#      response: DEBUG
# For also logging CF token retrieval, you may also add (Warning! This will expose internal and sensitive information in the logs!)
#      token: DEBUG
